language: c
dist: xenial

install:
  - wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.gz -O nasm-2.14.02.tar.gz
  - tar -xvf nasm-2.14.02.tar.gz
  - pushd nasm-2.14.02 && ./configure --prefix=/usr && make && sudo make install && popd

jobs:
  include:
   # General Linux build job
   - name: Build
     script:
     - cd build/linux
     - ./configure
     - make -j

